- time: 0
  stand_swing:
   position: [0, -95, 0]
   orientation: [0, 0, 0] 
  stand_com:
   position: [0, -47.5, 310]
   orientation: [0, 0, 0]
  left_hand: [0, -1.37, 0]
  right_hand: [0, 1.37, 0]
- time: 0.5
  stand_swing:
   position: [0, -95, 20]
   orientation: [0, 0, 0] 
  stand_com:
   position: [0, -47.5, 310]
   orientation: [0, 0, 0]
  left_hand: [0, -1.37, 0]
  right_hand: [0, 1.37, 0]
- time: 1
  stand_swing:
   position: [0, -95, 0]
   orientation: [0, 0, 0] 
  stand_com:
   position: [0, -47.5, 310]
   orientation: [0, 0, 0]
  left_hand: [0, -1.37, 0]
  right_hand: [0, 1.37, 0]
