cognition:
  ball_perceptor:
    ball_pixel_skip: 3
    diameter_pixel_offset: 2.5
    max_color_distance: 50
    max_noise_skipping: 5
    max_radius: 50
    max_std_dev: 0.5
    min_ball_size: 4
    min_eccentricity: 0.5
    min_valid_points: 5
    refine_max_color_distance: 50
    refine_max_pixel_count: 5
  camera:
    auto_white_balance: 0
    backlight_compensation: 0
    brightness: 128
    contrast: 128
    exposure_absolute: 300
    exposure_auto: 1
    focus_absolute: 0
    focus_auto: 0
    gain: 0
    power_line_frequency: 2
    saturation: 128
    sharpness: 0
    white_balance_temperature: 4500
  camera_info:
    height: 448
    horizontal_coverage_angle: 64
    optical_center_x: 400
    optical_center_y: 224
    vertical_coverage_angle: 38.17
    width: 800
  camera_pose:
    body_roll_correction_: 0
    body_tilt_correction_: 0
    body_translation_correction_x_: 0
    body_translation_correction_y_: 0
    body_translation_correction_z_: 0
    camera_pan_correction_: 0
    camera_roll_correction_: 0
    camera_tilt_correction_: 0.035
  color_mapping:
    max_distance: 15
    max_neighbours_: 3
  field_dimensions:
    ball_friction: 448
    ball_radius: 60
    center_circle_radius: 620
    field_lines_width: 50
    goal_height: 830
    goal_post_radius: 50
    x_pos_half_way_line: 0
    x_pos_opponent_drop_in_line: 448
    x_pos_opponent_field_border: 4570
    x_pos_opponent_goal: 4050
    x_pos_opponent_goal_post: 4030
    x_pos_opponent_groundline: 4000
    x_pos_opponent_penalty_area: 3400
    x_pos_opponent_penalty_mark: 2230
    x_pos_own_drop_in_line: 448
    x_pos_own_field_border: -4570
    x_pos_own_goal: -4050
    x_pos_own_goal_post: -4030
    x_pos_own_groundline: -4000
    x_pos_own_penalty_area: -3400
    x_pos_own_penalty_mark: -2230
    x_pos_penalty_striker_start_position: 448
    y_pos_center_goal: 448
    y_pos_left_drop_in_line: 448
    y_pos_left_field_border: -2610
    y_pos_left_goal: 448
    y_pos_left_penalty_area: -1390
    y_pos_left_sideline: -2410
    y_pos_right_drop_in_line: 448
    y_pos_right_field_border: 2610
    y_pos_right_goal: 448
    y_pos_right_penalty_area: 1390
    y_pos_right_sideline: 2410
  goal_perceptor:
    post_quality: 25
    yellow_skipping: 3
  line_spot:
    max_line_neighbor_grey_skip: 50
    max_line_neighbor_none_ratio: 0.5
    max_line_neighbor_none_size: 999999
    min_line_neighbor_green_above_size: 30
    min_line_neighbor_green_below_size: 30
    min_line_neighbor_green_side_size: 20
    min_line_segment_count: 2
    min_line_single_segment_size: 300
    min_line_size: 10
  regioning:
    border_min_green: 8
    explor_step_size: 3
    grid_step_size: 6
    max_angle_diff: 0.3
    max_none_pixels: 7
    region_max_size: 7
    search_ball_grid_step_size: 4
    search_ball_start_time: 200
    skip_offset: 3
  world_model_provider:
    param1: 4
motion:
  calibrate_compass: 0
  cm904:
    acc:
      direction:
        x: 1
        y: 1
        z: 1
      gain:
        x: 3.9
        y: 3.9
        z: 3.9
      offset:
        x: -60
        y: 10
        z: 70
    angle:
      direction:
        pitch: -1
        roll: -1
        yaw: 1
      offset:
        pitch: -0.075
        roll: -0.01
        yaw: 0
    gyro:
      direction:
        x: -1
        y: -1
        z: 1
      gain:
        x: 8.75
        y: 8.75
        z: 8.75
      offset:
        x: 0
        y: 0
        z: 0
  dt: 0.02
  fall_down_detector:
    fall_down_angle_x: 55
    fall_down_angle_y: 45
    fall_time: 1000
    on_ground_angle: 75
    staggering_angle_x: 40
    staggering_angle_y: 30
  invert_walk:
    arm:
      elbow_pitch: -0.314159
      moving_hand:
        pitch:
          offset: 0.23
          origin: 0.24
      shoulder_roll: 1.34
    constant_offset:
      hip_pitch_offset: 0.09
    db_time_percent: 0.5
    desired_value:
      max:
        theta: 0.392699
        v: 30
        x: 100
        y: 100
      theta: 0
      v: 97
      x: 97
      y: 0
    fall_protection:
      Position:
        X:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Y:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Z:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
      Rotation:
        Pitch:
          kd: 0
          ki: 0
          kp: 0.09
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Roll:
          kd: 0
          ki: 0
          kp: 0.1
          magnitude: 1
          sign: 1
          tolerance: 0.00957
    foot_swing:
      alpha_z: 0.1
      height: 30
      y_lift: 0
    is_y_constant: 0
    moving_offsets:
      LAnklePitch:
        alpha: 0.1
        height: 0
      LHipPitch:
        alpha: 0.1
        height: 0
      LHipRoll:
        alpha: 0.1
        height: 0.09
      RAnklePitch:
        alpha: 0.1
        height: 0
      RHipPitch:
        alpha: 0.1
        height: 0
      RHipRoll:
        alpha: 0.1
        height: 0.1
      pendulum:
        torso_roll:
          alpha: 0.1
          height: 0
      torso_roll:
        alpha: 0.27
        height: 0.05
    pendulum:
      alpha: 0.84
      s: 80.6
      shift_theta: 0
      virtual_height: 500
      weigth_x: 10
      weigth_x_dot: 10
      x_lift: 0
      y_lift: 0
    robot_sitting_height: 20
    shift:
      x: 0
      y: 0
    test_inverse:
      left:
        rot_x: 0
        rot_y: 0
        rot_z: 0
        x: 0
        y: -95.25
        z: 380
      right:
        rot_x: 0
        rot_y: 0
        rot_z: 0
        x: 0
        y: 95.25
        z: 380
  motors:
    HeadPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    HeadYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LAnklePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LAnkleRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LElbowPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LKneePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LShoulderPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LShoulderRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RAnklePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RAnkleRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RElbowPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RKneePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RShoulderPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RShoulderRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
  rob_mech_inf:
    robot_dimensions:
      arm_offset:
        x: 0
        y: 131.5
        z: 306.75
      heightLeg5Joint: 40
      lengthBetweenLegs: 190.5
      lowerArmLength: 166.5
      lowerLegLength: 177
      upperArmLength: 198.2
      upperLegLength: 175
      yElbowShoulder: 35
      zLegJoint1ToHeadPan: 306.75
    ground_contact_detector:
      contactThreshold: 0.5
      loadThreshold: 0.18
      noContactThreshold: 0.8
      safeContactTime: 3300
      safeNoContactTime: 1000
    sensor_calibrator:
      bias_x_acc: 0
      bias_x_gyro: 0
      bias_y_acc: 0
      bias_y_gyro: 0
      bias_z_acc: 0
      bias_z_gyro: 0
