behavior:
  behavior_request_provider:
    run: 0
  body_behavior_provider:
    angle_to_ball_epsilon: 0.2
    angle_to_goal_epsilon: 0.2
    angle_to_goal_threshold_: 0.314159
    backward_pan_: 30
    distant_pid_vth_kd: 0
    distant_pid_vth_ki: 0
    distant_pid_vth_kp: 1
    distant_pid_vx_kd: 0
    distant_pid_vx_ki: 0
    distant_pid_vx_kp: 0.015
    distant_pid_vy_kd: 0
    distant_pid_vy_ki: 0
    distant_pid_vy_kp: 0.025
    dribble_x_desire_: 50
    go_for_ball_theta_threshold_: 0.785398
    goal_distant_desire_ready_state: 4000
    goal_distant_threshold_ready_state: 500
    goal_threshold_ready_state: 1000
    goal_x_desire_ready_state: 7000
    goal_y_desire_ready_state: 0
    max_own_ball_dist_x: 200
    max_own_ball_dist_y: 85
    min_own_ball_dist_x: 0
    min_own_ball_dist_y: -85
    near_pid_vth_kd: 0
    near_pid_vth_ki: 0
    near_pid_vth_kp: 9
    near_pid_vx_kd: 0
    near_pid_vx_ki: 0
    near_pid_vx_kp: 0.08
    near_pid_vy_kd: 0
    near_pid_vy_ki: 0
    near_pid_vy_kp: 1
    opponent_goal_first_half: 1.4137
    opponent_goal_oritentation: 5.78
    opponent_goal_second_half: 1.4137
    pid_time_interval: 0.1
    pid_vth_kd: 0
    pid_vth_ki: 0
    pid_vth_kp: 1
    pid_vx_kd: 0
    pid_vx_ki: 0
    pid_vx_kp: 1
    pid_vy_kd: 0
    pid_vy_ki: 0
    pid_vy_kp: 1
    positioning_theta_threshold_: 0.174533
    th_distant_assume: 1.07
    theta_max_speed: 20
    x_behind_ball_for_kick_epsilon: 15
    x_desire_sidewalk_: -400
    x_distant_assume: 900
    x_max_speed: 30
    x_own_the_ball_desire: 300
    x_own_the_ball_threshold: 110
    y_behind_ball_for_kick_epsilon: 15
    y_desire_sidewalk_: -500
    y_desire_sidewalk_offset_: 500
    y_distant_assume: 400
    y_max_speed: 100
    y_own_the_ball_left_foot_desire: -20
    y_own_the_ball_right_foot_desire: -55
    y_own_the_ball_threshold: 50
  game_controller:
    robot_number: 3
    team_number: 1
  head_behavior_provider:
    head_pan_step_for_search_for_ball: 0.1
    head_pan_step_for_search_step_0: 0.15
    head_pan_step_for_search_step_1: 0.13
    head_pan_step_for_search_step_2: 0.09
    head_tilt_step1: 1.5
    head_tilt_step2: 0.854
    head_tilt_step3: 0.3
    max_head_pan_step1: 1.0472
    max_head_pan_step2: 1.5708
    max_head_pan_step3: 1
    min_head_pan_step1: -1
    min_head_pan_step2: -1.5708
    min_head_pan_step3: -1.5708
    pid_pan_kd: 0
    pid_pan_ki: 0
    pid_pan_kp: 0.3
    pid_tilt_kd: 0
    pid_tilt_ki: 0
    pid_tilt_kp: 0.2
    pid_time_interval: 0.0333333
    run: 0
  soccer_behavior:
    angle_to_opponent_goal: 1.4137
    angle_to_opponent_goal_multiplier: 0.5
    angle_to_opponent_goal_threshold: 0.5
    field_length: 20
    left_kick_ball_max_position_y: 40
    left_kick_ball_min_position_y: 18
    left_kick_ball_position_x: 150
    left_kick_ball_position_x_threshold: 50
    left_kick_ball_position_y: 50
    left_kick_ball_position_y_threshold: 50
    max_own_ball_dist_x: 175
    max_own_ball_dist_y: 85
    max_seconds_goal_must_seen: 5
    min_own_ball_dist_x: 100
    min_own_ball_dist_y: 10
    opponent_goal_oritentation: 40
    orientation_treshold: 5
    own_goal_oritentaion: 164
    right_kick_ball_min_position_y: 50
    right_kick_ball_position_x: 50
    right_kick_ball_position_x_threshold: 50
    right_kick_ball_position_y: 50
    right_kick_ball_position_y_threshold: 50
    run: 0
    search_move_cycles: 45
    seconds_before_search_for_ball: 2.5
    shoot_distance_x: 20
    turn_to_goal_theta: 10
    turn_to_goal_y: 0
cognition:
  ball_perceptor:
    ball_pixel_skip: 100
    diameter_pixel_offset: 2.5
    extends:
      ball_pixel_skip: 1
      diameter_pixel_offset: 2.5
      max_color_distance: 1
      max_noise_skipping: 1
      refine_max_color_distance: 40
      refine_max_pixel_count: 2
    filters:
      max_radius: 800
      max_std_dev: 0.5
      min_ball_size: 1
      min_eccentricity: 0.5
      min_valid_points: 4
    max_color_distance: 50
    max_noise_skipping: 5
    max_radius: 90
    max_std_dev: 0.5
    min_ball_size: 4
    min_eccentricity: 0.5
    min_valid_points: 5
    refine_max_color_distance: 50
    refine_max_pixel_count: 5
    weights:
      aspect_ratio_weight_: 50
      default_green_pixels_: 0.3
      default_orange_pixels_: 0.1
      default_white_pixels_: 0.1
      diff_center_weight_: 80
      dist_to_ball_ratio_weight_: 80
      eccentricity_weight_: 80
      min_spot_validity_: 50
      radius_ratio_weight_: 20
      std_dev_weight_: 80
  camera:
    auto_white_balance: 0
    backlight_compensation: 0
    brightness: 100
    contrast: 150
    exposure_absolute: 320
    exposure_auto: 1
    focus_absolute: 5
    focus_auto: 0
    gain: 10
    hue: 0
    power_line_frequency: 0
    saturation: 150
    sharpness: 0
    white_balance_temperature: 4000
  camera_info:
    height: 448
    horizontal_coverage_angle: 64
    optical_center_x: 400
    optical_center_y: 224
    vertical_coverage_angle: 38
    width: 800
  camera_pose:
    body_roll_correction_: 0
    body_tilt_correction_: 0
    body_translation_correction_x_: 0
    body_translation_correction_y_: 0
    body_translation_correction_z_: 0
    camera_pan_correction_: 0
    camera_roll_correction_: 0
    camera_tilt_correction_: 0.2
  color_mapping:
    max_distance: 10
    max_neighbours_: 3
  field_dimensions:
    ball_friction: 448
    ball_radius: 100
    center_circle_radius: 800
    field_lines_width: 50
    goal_height: 830
    goal_post_radius: 50
    x_pos_half_way_line: 0
    x_pos_opponent_drop_in_line: 448
    x_pos_opponent_field_border: 4570
    x_pos_opponent_goal: 4050
    x_pos_opponent_goal_post: 4030
    x_pos_opponent_groundline: 4000
    x_pos_opponent_penalty_area: 3400
    x_pos_opponent_penalty_mark: 2230
    x_pos_own_drop_in_line: 448
    x_pos_own_field_border: -4570
    x_pos_own_goal: -4050
    x_pos_own_goal_post: -4030
    x_pos_own_groundline: -4000
    x_pos_own_penalty_area: -3400
    x_pos_own_penalty_mark: -2230
    x_pos_penalty_striker_start_position: 448
    y_pos_center_goal: 448
    y_pos_left_drop_in_line: 448
    y_pos_left_field_border: -2610
    y_pos_left_goal: 448
    y_pos_left_penalty_area: -1390
    y_pos_left_sideline: -2410
    y_pos_right_drop_in_line: 448
    y_pos_right_field_border: 2610
    y_pos_right_goal: 448
    y_pos_right_penalty_area: 1390
    y_pos_right_sideline: 2410
  goal_perceptor:
    post_quality: 25
    yellow_skipping: 3
  line_perceptor:
    circle_bigger_than_specified: 10
    circle_max_neigh_dist: 200
    circle_max_radius_error: 250
    circle_max_supporter_dist: 200
    circle_max_supporter_dist2: 300
    circle_min_segment_img_length: 32
    circle_min_segment_length: 0
    circle_min_supporters: 4
    max_T_from_end: 250
    max_alpha_diff: 0.5
    max_distance_diff: 50
    max_intersection_err: 40
    max_line_circle_dist: 250
    max_line_distance: 6000
    max_line_single_seg_dist: 500
    max_line_single_seg_dist2: 150
    max_line_unite_alpha_diff: 0.785398
    max_line_unite_dist: 100
    max_mid_line_to_circle_dist: 150
    max_overlap_length: 500
    min_T_to_end: 100
    min_hardcover: 0.6
    min_intersection_alpha_diff: 1.1781
    min_intersection_length: 700
    min_line_single_region_length: 400
    min_line_start_length: 50
    min_mid_line_length: 700
    min_supporters: 1
    min_width_ratio: 1.25
    spot:
      max_line_neighbor_grey_skip: 50
      max_line_neighbor_none_ratio: 0.5
      max_line_neighbor_none_size: 999999
      min_line_eccentricity: 80
      min_line_neighbor_green_above_size: 30
      min_line_neighbor_green_below_size: 30
      min_line_neighbor_green_side_size: 20
      min_line_segment_count: 2
      min_line_single_segment_size: 300
      min_line_size: 10
  line_spot:
    max_line_neighbor_grey_skip: 50
    max_line_neighbor_none_ratio: 0.5
    max_line_neighbor_none_size: 999999
    min_line_neighbor_green_above_size: 30
    min_line_neighbor_green_below_size: 30
    min_line_neighbor_green_side_size: 20
    min_line_segment_count: 2
    min_line_single_segment_size: 300
    min_line_size: 10
  localization:
    center_circle_dev_: 1.5
    corner_std_dev_: 1.5
    field_height_: 8000
    field_width_: 5600
    goal_post_std_dev_: 3
    num_of_samples_: 40
    ot_std_dev_: 3
    ox_std_dev_: 0.85
    oy_std_dev_: 0.85
    sample_dist_from_given_position_: 400
    sample_dist_from_real_: 400
    x_T_center_left_: 0
    x_T_center_right_: 5600
    x_X_center_left_: 2000
    x_X_center_right_: 3600
    x_opponent_L_left_: 0
    x_opponent_L_right_: 5600
    x_opponent_left_goal_post_: 1800
    x_opponent_right_goal_post_: 3800
    x_own_L_left_: 0
    x_own_L_right_: 5600
    x_own_left_goal_post_: 1800
    x_own_right_goal_post_: 3800
    y_T_center_left_: 4000
    y_T_center_right_: 4000
    y_X_center_left_: 4000
    y_X_center_right_: 4000
    y_opponent_L_left_: 8000
    y_opponent_L_right_: 8000
    y_opponent_left_goal_post_: 8000
    y_opponent_right_goal_post_: 8000
    y_own_L_left_: 0
    y_own_L_right_: 0
    y_own_left_goal_post_: 0
    y_own_right_goal_post_: 0
  regioning:
    border_min_green: 8
    explor_step_size: 10
    grid_step_size: 10
    length_ratio_of_segment_: 70
    max_angle_diff: 30
    max_none_pixels: 50
    max_point_distance_: 10
    region_max_size: 10
    search_ball_grid_step_size: 4
    search_ball_start_time: 200
    skip_offset: 5
    sobel_threshold_: 255
  world_model_provider:
    param1: 4
gc:
  robotNumber: 0
  teamNumber: 0
motion:
  calibrate_compass: 0
  cm904:
    acc:
      cov:
        x: 0.00306023
        y: 0.00198626
        z: 0.0227073
      direction:
        x: 1
        y: 1
        z: 1
      gain:
        x: 3.9
        y: 3.9
        z: 3.9
      offset:
        x: -150
        y: 10
        z: 110
    angle:
      direction:
        pitch: 1
        roll: 1
        yaw: 1
      offset:
        pitch: 0
        roll: 0
        yaw: 0
    calibrate_moving: 0
    calibrate_steady: 1
    compass:
      direction:
        x: -1
        y: -1
        z: 1
      gain:
        x: 8.75
        y: 8.75
        z: 8.75
      offset:
        x: 0
        y: 0
        z: 0
      value:
        x:
          max: 500
          min: 0
        y:
          max: 500
          min: 0
        z:
          max: 500
          min: 0
    gyro:
      cov:
        x: 0.00496669
        y: 0.253997
        z: 0.000560921
      direction:
        x: 1
        y: 1
        z: 1
      gain:
        x: 8.75
        y: 8.75
        z: 8.75
      offset:
        x: 0
        y: 0
        z: 0
  dt: 0.02
  fall_down_detector:
    fall_down_angle_x: 55
    fall_down_angle_y: 45
    fall_time: 1000
    on_ground_angle: 75
    staggering_angle_x: 40
    staggering_angle_y: 30
  get_data: 0
  invert_walk:
    arm:
      elbow_pitch: -0.314159
      moving_hand:
        pitch:
          offset: 0.23
          origin: 0.24
      shoulder_roll: 1.34
    constant_offset:
      hip_pitch_offset: 0.2
    db_time_percent: 0.5
    desired_value:
      max:
        theta: 0.3
        v: 150
        x: 150
        y: 100
      theta: 0.07
      v: 0
      x: 0
      y: 0
    fall_protection:
      Position:
        X:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Y:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Z:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
      Rotation:
        Pitch:
          kd: 0
          ki: 0
          kp: 0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Roll:
          kd: 0
          ki: 0
          kp: 0
          magnitude: 1
          sign: 1
          tolerance: 0.00957
    foot_swing:
      alpha_z: 0.1
      height: 30
      y_lift: 0
    is_y_constant: 0
    moving_offsets:
      LAnklePitch:
        alpha: 0.1
        height: 0
      LHipPitch:
        alpha: 0.1
        height: 0
      LHipRoll:
        alpha: 0.1
        height: 0.09
      RAnklePitch:
        alpha: 0.1
        height: 0
      RHipPitch:
        alpha: 0.1
        height: 0
      RHipRoll:
        alpha: 0.1
        height: 0.1
      pendulum:
        torso_roll:
          alpha: 0.1
          height: 0
      torso_roll:
        alpha: 0.27
        height: 0
    pendulum:
      alpha: 0.87
      s: 15.1
      shift_theta: 0
      virtual_height: 500
      weigth_x: 10
      weigth_x_dot: 10
      x_lift: 0
      y_lift: 0
    robot_sitting_height: 37.9
    shift:
      x: 10.8
      y: 7.3
    test_inverse:
      left:
        rot_x: 0
        rot_y: 0
        rot_z: 0
        x: 0
        y: -47.5
        z: 280
      right:
        rot_x: 0
        rot_y: 0
        rot_z: 0
        x: 0
        y: 47.5
        z: 280
  motors:
    HeadPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 0.314159
      min_angle: -0.314159
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    HeadYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 0.314159
      min_angle: -0.314159
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LAnklePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 1.26
      min_angle: -1.45
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LAnkleRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 0.67
      min_angle: -0.75
      p_gain: 4
      position_offset: 0.1
      zero_offset: 0
    LElbowPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 1.91
      min_angle: -1.98
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 1.46
      min_angle: -1.57
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 0.49
      min_angle: -0.36
      p_gain: 4
      position_offset: 0.1
      zero_offset: 0
    LHipYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 1.25
      min_angle: -0.53
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LKneePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2.36
      min_angle: -0.5
      p_gain: 4
      position_offset: 0.5
      zero_offset: 0
    LShoulderPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2.48
      min_angle: -3.14
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LShoulderRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 0.92
      min_angle: -1.47
      p_gain: 4
      position_offset: 0.1
      zero_offset: 0
    RAnklePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 1.26
      min_angle: -1.45
      p_gain: 4
      position_offset: 0.1
      zero_offset: 0
    RAnkleRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 0.67
      min_angle: -0.75
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RElbowPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 1.91
      min_angle: -1.98
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 1.46
      min_angle: -1.57
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 0.36
      min_angle: -0.49
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 0.64
      min_angle: -0.49
      p_gain: 4
      position_offset: 0.1
      zero_offset: 0
    RKneePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2.36
      min_angle: -0.5
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RShoulderPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 3.14
      min_angle: -2.48
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RShoulderRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 1.47
      min_angle: -0.92
      p_gain: 4
      position_offset: 0
      zero_offset: 0
  rob_mech_inf:
    ground_contact_detector:
      contactThreshold: 0.5
      loadThreshold: 0.18
      noContactThreshold: 0.8
      safeContactTime: 3300
      safeNoContactTime: 1000
    robot_dimensions:
      arm_offset:
        x: 0
        y: 78.1
        z: 159.5
      heightLeg5Joint: 39.1
      lengthBetweenLegs: 95
      lowerArmLength: 166.5
      lowerLegLength: 149
      upperArmLength: 144.8
      upperLegLength: 144.5
      xHeadTiltToCamera: 0
      yElbowShoulder: 35
      zHeadTiltToCamera: 0
      zLegJoint1ToHeadPan: 231.75
    sensor_calibrator:
      bias_x_acc: 0
      bias_x_gyro: 0
      bias_y_acc: 0
      bias_y_gyro: 0
      bias_z_acc: 0
      bias_z_gyro: 0
