behavior:
  behavior_request_provider:
    run: 0
  body_behavior_provider:
    angle_to_ball_epsilon: 0.2
    angle_to_goal_epsilon: 0.2
    x_behind_ball_for_kick_epsilon: 15
    y_behind_ball_for_kick_epsilon: 15
  head_behavior_provider:
    run: 0
  soccer_behavior:
    run: 0
cognition:
  ball_perceptor:
    ball_pixel_skip: 3
    diameter_pixel_offset: 2.5
    extends:
      ball_pixel_skip: 1
      diameter_pixel_offset: 2.5
      max_color_distance: 40
      max_noise_skipping: 1
      refine_max_color_distance: 40
      refine_max_pixel_count: 2
    filters:
      max_radius: 499.9
      max_std_dev: 0.5
      min_ball_size: 4
      min_eccentricity: 0.5
      min_valid_points: 4
    max_color_distance: 50
    max_noise_skipping: 5
    max_radius: 50
    max_std_dev: 0.5
    min_ball_size: 4
    min_eccentricity: 0.5
    min_valid_points: 5
    refine_max_color_distance: 50
    refine_max_pixel_count: 5
    weights:
      aspect_ratio_weight_: 50
      diff_center_weight_: 50
      dist_to_ball_ratio_weight_: 50
      eccentricity_weight_: 50
      min_spot_validity_: 50
      radius_ratio_weight_: 50
      std_dev_weight_: 50
  camera:
    auto_white_balance: 0
    backlight_compensation: 0
    brightness: 128
    contrast: 128
    exposure_absolute: 300
    exposure_auto: 1
    focus_absolute: 0
    focus_auto: 0
    gain: 0
    power_line_frequency: 2
    saturation: 128
    sharpness: 0
    white_balance_temperature: 4500
  camera_info:
    height: 448
    horizontal_coverage_angle: 64
    optical_center_x: 400
    optical_center_y: 224
    vertical_coverage_angle: 38.17
    width: 800
  camera_pose:
    body_roll_correction_: 0
    body_tilt_correction_: 0
    body_translation_correction_x_: 0
    body_translation_correction_y_: 0
    body_translation_correction_z_: 0
    camera_pan_correction_: 0
    camera_roll_correction_: 0
    camera_tilt_correction_: 0.035
  color_mapping:
    max_distance: 15
    max_neighbours_: 3
  field_dimensions:
    ball_friction: 448
    ball_radius: 60
    center_circle_radius: 620
    field_lines_width: 50
    goal_height: 830
    goal_post_radius: 50
    x_pos_half_way_line: 0
    x_pos_opponent_drop_in_line: 448
    x_pos_opponent_field_border: 4570
    x_pos_opponent_goal: 4050
    x_pos_opponent_goal_post: 4030
    x_pos_opponent_groundline: 4000
    x_pos_opponent_penalty_area: 3400
    x_pos_opponent_penalty_mark: 2230
    x_pos_own_drop_in_line: 448
    x_pos_own_field_border: -4570
    x_pos_own_goal: -4050
    x_pos_own_goal_post: -4030
    x_pos_own_groundline: -4000
    x_pos_own_penalty_area: -3400
    x_pos_own_penalty_mark: -2230
    x_pos_penalty_striker_start_position: 448
    y_pos_center_goal: 448
    y_pos_left_drop_in_line: 448
    y_pos_left_field_border: -2610
    y_pos_left_goal: 448
    y_pos_left_penalty_area: -1390
    y_pos_left_sideline: -2410
    y_pos_right_drop_in_line: 448
    y_pos_right_field_border: 2610
    y_pos_right_goal: 448
    y_pos_right_penalty_area: 1390
    y_pos_right_sideline: 2410
  goal_perceptor:
    post_quality: 25
    yellow_skipping: 3
  line_perceptor:
    circle_bigger_than_specified: 0
    circle_max_neigh_dist: 200
    circle_max_radius_error: 250
    circle_max_supporter_dist: 200
    circle_max_supporter_dist2: 300
    circle_min_segment_img_length: 32
    circle_min_segment_length: 0
    circle_min_supporters: 4
    max_T_from_end: 250
    max_alpha_diff: 0.15
    max_distance_diff: 150
    max_line_circle_dist: 250
    max_line_distance: 6000
    max_line_single_seg_dist: 150
    max_line_single_seg_dist2: 250
    max_line_unite_alpha_diff: 0.785398
    max_line_unite_dist: 175
    max_mid_line_to_circle_dist: 150
    max_overlap_length: 500
    min_T_to_end: 250
    min_hardcover: 0.6
    min_intersection_alpha_diff: 1.1781
    min_intersection_length: 700
    min_line_single_region_length: 400
    min_line_start_length: 50
    min_mid_line_length: 700
    min_supporters: 1
    min_width_ratio: 1.25
    spot:
      max_line_neighbor_grey_skip: 50
      max_line_neighbor_none_ratio: 0.5
      max_line_neighbor_none_size: 999999
      min_line_neighbor_green_above_size: 30
      min_line_neighbor_green_below_size: 30
      min_line_neighbor_green_side_size: 20
      min_line_segment_count: 2
      min_line_single_segment_size: 300
      min_line_size: 10
  line_spot:
    max_line_neighbor_grey_skip: 50
    max_line_neighbor_none_ratio: 0.5
    max_line_neighbor_none_size: 999999
    min_line_neighbor_green_above_size: 30
    min_line_neighbor_green_below_size: 30
    min_line_neighbor_green_side_size: 20
    min_line_segment_count: 2
    min_line_single_segment_size: 300
    min_line_size: 10
  regioning:
    border_min_green: 8
    explor_step_size: 3
    grid_step_size: 6
    max_angle_diff: 0.3
    max_none_pixels: 7
    region_max_size: 7
    search_ball_grid_step_size: 4
    search_ball_start_time: 200
    skip_offset: 3
  world_model_provider:
    param1: 4
gc:
  robotNumber: 0
  teamNumber: 0
motion:
  calibrate_compass: 0
  cm904:
    acc:
      cov:
        x: 0.0017707
        y: 0.00281387
        z: 0.0134111
      direction:
        x: 1
        y: 1
        z: 1
      gain:
        x: 3.9
        y: 3.9
        z: 3.9
      offset:
        x: -139
        y: -14
        z: 66
    angle:
      direction:
        pitch: 1
        roll: 1
        yaw: 1
      offset:
        pitch: 0.1
        roll: 0
        yaw: 0
    calibrate_moving: 0
    calibrate_steady: 1
    compass:
      direction:
        x: -1
        y: -1
        z: 1
      gain:
        x: 8.75
        y: 8.75
        z: 8.75
      offset:
        x: 0
        y: 0
        z: 0
      value:
        x:
          max: 770
          min: -3351.25
        y:
          max: -3981.25
          min: -6020
        z:
          max: -332.5
          min: -2983.75
    gyro:
      cov:
        x: 0.00118047
        y: 0.23781
        z: 0.00063567
      direction:
        x: 1
        y: 1
        z: 1
      gain:
        x: 8.75
        y: 8.75
        z: 8.75
      offset:
        x: 0
        y: 0
        z: 0
  dt: 0.02
  fall_down_detector:
    fall_down_angle_x: 55
    fall_down_angle_y: 45
    fall_time: 1000
    on_ground_angle: 75
    staggering_angle_x: 40
    staggering_angle_y: 30
  get_data: 0
  invert_walk:
    arm:
      elbow_pitch: -0.314159
      moving_hand:
        pitch:
          offset: 0.23
          origin: 0.24
      shoulder_roll: 1.34
    constant_offset:
      hip_pitch_offset: 0.2
    db_time_percent: 0.5
    desired_value:
      max:
        theta: 0.392699
        v: 30
        x: 100
        y: 100
      theta: 0.07
      v: 0
      x: -150
      y: 0
    fall_protection:
      Position:
        X:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Y:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Z:
          kd: 0
          ki: 0
          kp: 0.0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
      Rotation:
        Pitch:
          kd: 0
          ki: 0
          kp: 0
          magnitude: 1
          sign: 1
          tolerance: 0.0001
        Roll:
          kd: 0
          ki: 0
          kp: 0
          magnitude: 1
          sign: 1
          tolerance: 0.00957
    foot_swing:
      alpha_z: 0.1
      height: 30
      y_lift: 0
    is_y_constant: 0
    moving_offsets:
      LAnklePitch:
        alpha: 0.1
        height: 0
      LHipPitch:
        alpha: 0.1
        height: 0
      LHipRoll:
        alpha: 0.1
        height: 0.09
      RAnklePitch:
        alpha: 0.1
        height: 0
      RHipPitch:
        alpha: 0.1
        height: 0
      RHipRoll:
        alpha: 0.1
        height: 0.1
      pendulum:
        torso_roll:
          alpha: 0.1
          height: 0
      torso_roll:
        alpha: 0.27
        height: 0
    pendulum:
      alpha: 0.87
      s: 15.1
      shift_theta: 0
      virtual_height: 500
      weigth_x: 10
      weigth_x_dot: 10
      x_lift: 0
      y_lift: 0
    robot_sitting_height: 37.9
    shift:
      x: 10.8
      y: 7.3
    test_inverse:
      left:
        rot_x: 0
        rot_y: 0
        rot_z: 0
        x: 0
        y: -47.5
        z: 280
      right:
        rot_x: 0
        rot_y: 0
        rot_z: 0
        x: 0
        y: 47.5
        z: 280
  motors:
    HeadPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    HeadYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LAnklePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LAnkleRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LElbowPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LHipYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LKneePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LShoulderPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    LShoulderRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RAnklePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RAnkleRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 0
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RElbowPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RHipYaw:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RKneePitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RShoulderPitch:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
    RShoulderRoll:
      calibration_mode: 0
      d_gain: 0
      i_gain: 0
      is_flipped: 1
      max_angle: 2100
      min_angle: 2000
      p_gain: 4
      position_offset: 0
      zero_offset: 0
  rob_mech_inf:
    ground_contact_detector:
      contactThreshold: 0.5
      loadThreshold: 0.18
      noContactThreshold: 0.8
      safeContactTime: 3300
      safeNoContactTime: 1000
    robot_dimensions:
      arm_offset:
        x: 0
        y: 78.1
        z: 159.5
      heightLeg5Joint: 39.1
      lengthBetweenLegs: 95
      lowerArmLength: 166.5
      lowerLegLength: 149
      upperArmLength: 144.8
      upperLegLength: 144.5
      xHeadTiltToCamera: 25.05
      yElbowShoulder: 35
      zHeadTiltToCamera: 66.9
      zLegJoint1ToHeadPan: 231.75
    sensor_calibrator:
      bias_x_acc: 0
      bias_x_gyro: 0
      bias_y_acc: 0
      bias_y_gyro: 0
      bias_z_acc: 0
      bias_z_gyro: 0
